import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:imagia_mobile/mosaic/matching.dart';
import 'package:imagia_mobile/mosaic/shared.dart';
import 'package:imagia_mobile/mosaic/types.dart';

/// Fidelity harness (layer 1 — bit-exact pure algorithm).
///
/// Loads `test/fixtures/fidelity_core.json`, generated by the REAL web
/// algorithm via `foto-mozaik/scripts/mosaic-fidelity-gen.ts`, and asserts the
/// Dart port reproduces:
///   - every pure scoring function (bit-exact),
///   - the initial 13-signal selection (tileId + score),
///   - a full simulated-annealing run from a fixed seed (placement-for-placement).
///
/// IEEE-754 float64 arithmetic (+, -, *, /, sqrt) is identical across V8 and
/// the Dart VM, so these are exact. `exp`/`log` may differ by ≤1 ULP between
/// math libraries; if a future fixture exercises those into an SA acceptance
/// boundary it could diverge — none observed here.

LabColor _lab(Map<String, dynamic> j) => LabColor.fromJson(j);
RgbColor _rgb(Map<String, dynamic> j) => RgbColor.fromJson(j);
List<LabColor> _labs(dynamic v) =>
    (v as List).map((e) => _lab((e as Map).cast<String, dynamic>())).toList();
List<double> _nums(dynamic v) =>
    (v as List).map((e) => (e as num).toDouble()).toList();

void main() {
  final file = File('test/fixtures/fidelity_core.json');
  final fixture =
      jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;

  final settings = MosaicSettings.fromJson(
      (fixture['settings'] as Map).cast<String, dynamic>());
  final tiles = (fixture['tiles'] as List)
      .map((e) => TileDescriptor.fromJson((e as Map).cast<String, dynamic>()))
      .toList();
  final regions = (fixture['regions'] as List)
      .map((e) => RegionAnalysis.fromJson((e as Map).cast<String, dynamic>()))
      .toList();
  final checks = (fixture['pureChecks'] as Map).cast<String, dynamic>();

  group('pure functions are bit-exact', () {
    // rgbToLab (cbrt) and aspectPenalty (log) depend on transcendental
    // functions whose last-ULP rounding is libm-specific (V8 vs Dart VM). They
    // are asserted to <1e-9 rather than bit-exact — this difference is far
    // below the float32 pixel-decode noise floor and is mathematically
    // inherent, not a port bug. Everything else below is bit-exact.
    test('rgbToLab', () {
      for (final c in checks['rgbToLab'] as List) {
        final m = (c as Map).cast<String, dynamic>();
        final out = rgbToLab(_rgb((m['in'] as Map).cast<String, dynamic>()));
        final exp = _lab((m['out'] as Map).cast<String, dynamic>());
        expect(out.L, closeTo(exp.L, 1e-9));
        expect(out.a, closeTo(exp.a, 1e-9));
        expect(out.b, closeTo(exp.b, 1e-9));
      }
    });

    test('labDistance', () {
      for (final c in checks['labDistance'] as List) {
        final m = (c as Map).cast<String, dynamic>();
        final out = labDistance(_lab((m['a'] as Map).cast<String, dynamic>()),
            _lab((m['b'] as Map).cast<String, dynamic>()));
        expect(out, (m['out'] as num).toDouble());
      }
    });

    test('aspectPenalty', () {
      for (final c in checks['aspectPenalty'] as List) {
        final m = (c as Map).cast<String, dynamic>();
        final out = aspectPenalty(
            (m['tileAR'] as num).toDouble(), (m['regionAR'] as num).toDouble());
        expect(out, closeTo((m['out'] as num).toDouble(), 1e-9));
      }
    });

    test('luminancePatternDistance & chromaPatternDistance', () {
      for (final c in checks['luminancePattern'] as List) {
        final m = (c as Map).cast<String, dynamic>();
        expect(luminancePatternDistance(_labs(m['a']), _labs(m['b'])),
            (m['out'] as num).toDouble());
      }
      for (final c in checks['chromaPattern'] as List) {
        final m = (c as Map).cast<String, dynamic>();
        expect(chromaPatternDistance(_labs(m['a']), _labs(m['b'])),
            (m['out'] as num).toDouble());
      }
    });

    test('edgePatternDistance & contrastPatternDistance', () {
      for (final c in checks['edgePattern'] as List) {
        final m = (c as Map).cast<String, dynamic>();
        expect(edgePatternDistance(_nums(m['a']), _nums(m['b'])),
            (m['out'] as num).toDouble());
      }
      for (final c in checks['contrastPattern'] as List) {
        final m = (c as Map).cast<String, dynamic>();
        expect(contrastPatternDistance(_nums(m['a']), _nums(m['b'])),
            (m['out'] as num).toDouble());
      }
    });

    test('histogramDistance', () {
      for (final c in checks['histogram'] as List) {
        final m = (c as Map).cast<String, dynamic>();
        expect(histogramDistance(_nums(m['a']), _nums(m['b'])),
            (m['out'] as num).toDouble());
      }
    });

    test('computeCropWeights', () {
      for (final c in checks['cropWeights'] as List) {
        final m = (c as Map).cast<String, dynamic>();
        final out = computeCropWeights(
            (m['tileAR'] as num).toDouble(), (m['cellAR'] as num).toDouble());
        if (m['out'] == null) {
          expect(out, isNull);
        } else {
          final exp = _nums(m['out']);
          expect(out, isNotNull);
          for (var i = 0; i < 25; i++) {
            expect(out![i], exp[i], reason: 'crop weight $i');
          }
        }
      }
    });
  });

  test('initial selection (selectBestTileMatch) matches', () {
    final ref = (fixture['selectBestMatch'] as List)
        .map((e) => (e as Map).cast<String, dynamic>())
        .toList();
    for (var i = 0; i < regions.length; i++) {
      final m = selectBestTileMatch(MatchInput(
        region: regions[i],
        tiles: tiles,
        settings: settings,
        usageCounts: {},
      ));
      expect(m.tile.id, ref[i]['tileId'], reason: 'region $i tileId');
      expect(m.score, (ref[i]['score'] as num).toDouble(),
          reason: 'region $i score');
    }
  });

  test('simulated annealing reproduces placement-for-placement', () {
    final meta = (fixture['meta'] as Map).cast<String, dynamic>();
    final numTiles = meta['numTiles'] as int;
    final grid = meta['grid'] as int;

    // Same fixed initial assignment as the reference: index % numTiles.
    final placements = <MosaicPlacement>[];
    for (var i = 0; i < regions.length; i++) {
      final tile = tiles[i % numTiles];
      placements.add(regions[i].toPlacement(i, tile.id, tile.name, 0));
    }
    final tileMap = {for (final t in tiles) t.id: t};

    // Same 4-neighbour grid adjacency.
    final adjacency = List<Set<int>>.generate(regions.length, (_) => <int>{});
    for (var gy = 0; gy < grid; gy++) {
      for (var gx = 0; gx < grid; gx++) {
        final idx = gy * grid + gx;
        if (gx > 0) adjacency[idx].add(idx - 1);
        if (gx < grid - 1) adjacency[idx].add(idx + 1);
        if (gy > 0) adjacency[idx].add(idx - grid);
        if (gy < grid - 1) adjacency[idx].add(idx + grid);
      }
    }

    optimizePlacementSwaps(placements, tileMap, settings,
        adjacency: adjacency, seedOffset: 0);

    final ref = (fixture['saResult'] as Map).cast<String, dynamic>();
    final refTileIds = (ref['tileIds'] as List).cast<String>();
    final refScores = _nums(ref['scores']);

    final outTileIds = placements.map((p) => p.tileId).toList();
    expect(outTileIds, refTileIds, reason: 'SA tileId sequence diverged');
    for (var i = 0; i < placements.length; i++) {
      expect(placements[i].score, refScores[i], reason: 'SA score $i');
    }
  });
}
